### ISSUE TITLE
predicted value missing from graph

### ISSUE THREAD

**Issue by michaelneale** [cloudwalkio/omg-monitor#37]
I am sure it used to show a predicted line following the actual values on the graph - this has disappeared recently?

**Comment by allanino** [comment]
Oh, I'm sorry about changing that without notice!

When I moved from pure D3.js to dygraphs, I added some options to customize the graphs and I decided not to show the predicted values by default, as most important is the anomalies (in my perspective). You can see the predicted values passing an URL parameter `debug=true`.

A full list of all allowed URL parameters can be found in [this wiki page](https://github.com/cloudwalkio/omg-monitor/wiki/API-Client).

**Comment by michaelneale** [comment]
Cheers- perfect.

**Comment by allanino** [comment]
Thanks! So I'm closing this.
