### ISSUE TITLE
return more values (predicted, and more) from dynamic monitor

### ISSUE THREAD

**Issue by michaelneale** [cloudwalkio/omg-monitor#42]
Hey @allanino  - thinking aloud (we should find a media to converse in other than github tickets!): 

I am looking at possibly returning more data from the _dyn check - ie predicted value - and also considering providing some limited window of historical data as "evidence". So when it returns its "verdict' there is enough info returned to help provide evidence (eg a little graph). Thoughts? Or should this be "pulled" from the server on the other port? (seems a tad clumsy, but can work).

**Comment by allanino** [comment]
Hey @michaelneale!

I think it would be better just to use the API served by the Martini server (solution which you call clumsy) :) 

That will keep things simple. You'll just need to do something like this:
```
# Get 10 last data points for monitor mic3
points_to_get = 10
monitor_id = 'mic3'
response = requests.get('http://localhost:5000/results/%s?limit=%d' % (monitor_id, points_to_get))

#Extract (value, prediction) list
value_prediction_pairs = [(r['raw_value'], r['predicted']) for r in response.json()['results']]
```

Then you could use this information for any purpose you want, like for these little graphs (ASCII?).

What do you think?

**Comment by michaelneale** [comment]
yeah - I am more thinking I could also expose that via the python webapp -
(just one less port to map) - but yeah - your point remains.
